###服务端口号
server:
  port: 8200
spring:
  application:
    name: app-euerke-sms
###eureka 基本信息配置
eureka:
  instance:
    ###注册到eurekaip地址
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8100/eureka/
    register-with-eureka: true
    fetch-registry: true

###########Swagger配置
swagger:
  base-package: com.mayi.edu.sms.service
  title: SpringCloud2.0x构建的微服务电商项目
